export const addNewRestaurantModal = {
  heading: "Add New Restaurant",
  formFields: [
    {
      label: "Restaurant Name",
      type: "text",
      placeholder: "Enter restaurant name",
      required: true,
      name: "name",
      error: "Name is required",
    },
    {
      label: "Restaurant Address",
      type: "textarea",
      placeholder: "Enter restaurant adress",
      required: true,
      name: "address",
      error: "Address is required",
    },
    {
      label: "Restaurant Area",
      type: "text",
      placeholder: "Enter restaurant area",
      required: true,
      name: "area",
      error: "Restaurant area is required",
    },
    {
      label: "Restaurant City",
      type: "text",
      placeholder: "Enter restaurant city",
      required: true,
      name: "city",
      error: "Restaurant city is required",
    },
    {
      label: "Restaurant State",
      type: "text",
      placeholder: "Enter restaurant state",
      required: true,
      name: "state",
      error: "Restaurant state is required",
    },
    {
      label: "Restaurant Email",
      type: "text",
      placeholder: "Enter restaurant email",
      required: true,
      name: "email",
      error: "Restaurant email is required",
    },

    {
      label: "Restaurant Number",
      type: "number",
      placeholder: "Enter restaurant contact",
      required: true,
      name: "contact",
      error: "Restaurant contact is required",
    },
    {
      label: "Restaurant Alternate Contact",
      type: "number",
      placeholder: "Enter restaurant alternateContact",
      required: false,
      name: "alternateContact",
    },
    {
      label: "Restaurant GST number",
      type: "text",
      placeholder: "Enter restaurant GST number",
      required: true,
      name: "gst",
      error: "GST is required",
    },
  ],
};
